
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lojchdvtwypjqupsjynf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvamNoZHZ0d3lwanF1cHNqeW5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1Nzg0MDYsImV4cCI6MjA1OTE1NDQwNn0.49LcAgTWWV8AOopIV5xlhUARojsTHZTqA_fYPtvtyJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true
    },
    global: {
      headers: {
        'x-client-info': 'lovable-email-app'
      },
      fetch: (url, options) => {
        // Add a request timestamp to prevent caching
        const urlObj = new URL(url);
        
        // Handle Supabase RLS timestamp filter issues
        // Skip adding timestamp to database queries as this causes filtering issues
        if (!url.includes('/rest/v1/')) {
          urlObj.searchParams.set('_t', Date.now().toString());
        }
        
        return fetch(urlObj.toString(), {
          ...options,
          credentials: 'same-origin'
        });
      }
    }
  }
);

// Helper to check the auth state
export const checkSupabaseConnection = async () => {
  try {
    console.log("Checking Supabase connection status...");
    
    // First try to get the session
    const { data: sessionData, error: sessionError } = await supabase.auth.getSession();
    
    if (sessionError) {
      console.error("Supabase session error:", sessionError);
      return {
        connected: false,
        error: `Authentication error: ${sessionError.message}`
      };
    }
    
    // Then test the connection to edge functions
    try {
      // Add a timestamp to prevent caching
      const timestamp = new Date().getTime();
      
      const { error: functionError } = await supabase.functions.invoke('check-resend-status', {
        body: { 
          timestamp,
          connectionTest: true 
        }
      });
      
      if (functionError) {
        console.error("Edge function connection error:", functionError);
        return {
          connected: true,
          edgeFunctionsConnected: false,
          session: sessionData.session,
          isSignedIn: !!sessionData.session,
          error: `Edge functions not reachable: ${functionError.message}`
        };
      }
      
      return {
        connected: true,
        edgeFunctionsConnected: true,
        session: sessionData.session,
        isSignedIn: !!sessionData.session
      };
    } catch (functionErr) {
      console.error("Error testing edge function connectivity:", functionErr);
      
      return {
        connected: true,
        edgeFunctionsConnected: false,
        session: sessionData.session,
        isSignedIn: !!sessionData.session,
        error: functionErr instanceof Error ? functionErr.message : 'Unknown error connecting to edge functions'
      };
    }
  } catch (err) {
    console.error("Error checking Supabase connection:", err);
    return {
      connected: false,
      error: err instanceof Error ? err.message : 'Unknown error'
    };
  }
};

// Helper to retry failed operations with exponential backoff
export const retryOperation = async <T>(
  operation: () => Promise<T>,
  maxRetries: number = 3,
  delay: number = 1000
): Promise<T> => {
  let lastError: any;
  
  for (let attempt = 0; attempt < maxRetries; attempt++) {
    try {
      return await operation();
    } catch (error) {
      console.warn(`Operation failed (attempt ${attempt + 1}/${maxRetries}):`, error);
      lastError = error;
      
      // Exponential backoff with jitter
      const jitter = Math.random() * 0.3 + 0.85; // Random factor between 0.85 and 1.15
      const waitTime = delay * Math.pow(2, attempt) * jitter;
      
      await new Promise(resolve => setTimeout(resolve, waitTime));
    }
  }
  
  throw lastError;
};
