// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lojchdvtwypjqupsjynf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvamNoZHZ0d3lwanF1cHNqeW5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1Nzg0MDYsImV4cCI6MjA1OTE1NDQwNn0.49LcAgTWWV8AOopIV5xlhUARojsTHZTqA_fYPtvtyJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);