
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lojchdvtwypjqupsjynf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvamNoZHZ0d3lwanF1cHNqeW5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1Nzg0MDYsImV4cCI6MjA1OTE1NDQwNn0.49LcAgTWWV8AOopIV5xlhUARojsTHZTqA_fYPtvtyJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true
    },
    global: {
      headers: {
        'x-client-info': 'lovable-email-app'
      },
      fetch: (url, options) => {
        // Add a request timestamp to prevent caching
        const urlObj = new URL(url);
        urlObj.searchParams.set('_t', Date.now().toString());
        return fetch(urlObj.toString(), {
          ...options,
          credentials: 'same-origin'
        });
      }
    }
  }
);

// Helper to check the auth state
export const checkSupabaseConnection = async () => {
  try {
    const { data, error } = await supabase.auth.getSession();
    if (error) {
      console.error("Supabase connection error:", error);
      return {
        connected: false,
        error: error.message
      };
    }
    
    // Test connection to an edge function
    try {
      const { error: functionError } = await supabase.functions.invoke('check-resend-status', {
        body: { connectionTest: true }
      });
      
      if (functionError) {
        console.error("Edge function connection error:", functionError);
        return {
          connected: true,
          edgeFunctionsConnected: false,
          session: data.session,
          isSignedIn: !!data.session,
          error: `Edge functions not reachable: ${functionError.message}`
        };
      }
    } catch (functionErr) {
      console.error("Error testing edge function connectivity:", functionErr);
    }
    
    return {
      connected: true,
      edgeFunctionsConnected: true,
      session: data.session,
      isSignedIn: !!data.session
    };
  } catch (err) {
    console.error("Error checking Supabase connection:", err);
    return {
      connected: false,
      error: err instanceof Error ? err.message : 'Unknown error'
    };
  }
};
